### PR TITLE
ISSUE-50: Create ci.yml (#1)

### LINKED ISSUE #50: Migrate to Github Actions?
# Overview

We migrated Frictionless-py to Github Actions as Travis CI seems to be dying. Github Actions has been really great so far and simple to migrate to.

### PR DESCRIPTION
**Pull request by DiegoPino**
See #50
 
# Overview
Creates a ci.yml Github Action using PHP 7.1 and the composer-php plugin

## Note for everyone:
Should we waste Earth resources (a.k.a as Global Warming is a real issue) testing every PHP version? I would say no, not my choice of computing use. But open to hear more about that if you feel we should

Adds PHP 7.1/Composer Github action for Pushes and Pulls against Master. Will also remove some oldies in this pass.

@roll @lwinfree

### CODE REVIEW

**Comment by DiegoPino** [comment]
@roll @lwinfree the CI/Build fails but its not because of me. Since I'm making a pull from my Fork there is a Cross Repository Permissions issue where this one (the receiver) has not permission to run on the other. You can check the CI actually passes. https://github.com/DiegoPino/datapackage-php/actions/runs/1125959359

If you feel unsure about _me_ merging this as IT is, then what I can do is to make a pull first against a New ISSUE-50 branch on this repo and merge. Then I can do from the same repo another one. Just in case. Next step (tomorrow afternoon) is to prepare a release. BUT! table schema repo is still on 0.2 and it would be so great if we could get both repo's moving into 1.0.0 at the same time. I can also make an Github Action CI pull against that one to equalize.

**Comment by roll** [comment]
Hi @DiegoPino,

Sorry, it seems we have forgotten to add you to the PHP team. I've sent an invite now. You should have maintainer permissions after accepting it.

I think a few latest versions are enough. Usually, we do something like this for other languages.

**Comment by DiegoPino** [comment]
@roll thanks. Will test against the margins. 7.1 and 7.4. The PHP 8.0 is a larger refactor and I may take that as a Fall task for version 1.1.0

**Comment by roll** [comment]
@DiegoPino 
Great! Thanks for working on this!

**Pull request merged**
